import type { Product } from "./types";

export const carParts: Product[] = [
  {
    id: "car1",
    slug: "car-engine-oil-filter",
    name: "Premium Engine Oil Filter",
    description: "High-performance engine oil filter for optimal engine protection and longevity.",
    price: 29.99,
    compareAtPrice: 49.99,
    category: "car-parts",
    tags: ["engine", "filter", "oil", "maintenance"],
    image: "https://images.unsplash.com/photo-1586201375761-83865001e8ce?w=500&auto=format&fit=crop&q=60",
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e8ce?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1620889543939-6c4a3c3b9d8e?w=500&auto=format&fit=crop&q=60",
    ],
    rating: 4.7,
    reviewCount: 89,
    createdAt: "2026-06-15",
    status: "live",
    weight: "1.2kg",
    inventory: 156,
    shippingFrom: "China",
    shippingMethods: [
      {
        name: "Standard Shipping",
        fee: 8.99,
        processingDays: "3-5 days",
        deliveryDays: "7-12 days",
        tracking: "Full tracking",
      },
      {
        name: "Express Shipping",
        fee: 15.99,
        processingDays: "1-2 days",
        deliveryDays: "3-5 days",
        tracking: "Full tracking",
      },
    ],
    totalLandedCost: 45.98,
    supplier: {
      source: "cj-dropshipping",
      sku: "CAR-OIL-FILTER-001",
      costPrice: 22.50,
      shippingDays: "5",
      shippingFee: 8.99,
      processingTime: "3-5 days",
      notes: "High-quality synthetic filter material",
    },
  },
  {
    id: "car2",
    slug: "car-brake-pads",
    name: "Ceramic Brake Pads",
    description: "Premium ceramic brake pads with low dust formulation for smooth, quiet braking performance.",
    price: 79.99,
    compareAtPrice: 129.99,
    category: "car-parts",
    tags: ["brakes", "ceramic", "safety", "maintenance"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop&q=60",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1620889543939-6c4a3c3b9d8e?w=500&auto=format&fit=crop&q=60",
    ],
    rating: 4.8,
    reviewCount: 124,
    createdAt: "2026-06-10",
    status: "live",
    weight: "3.5kg",
    inventory: 89,
    shippingFrom: "China",
    shippingMethods: [
      {
        name: "Standard Shipping",
        fee: 12.99,
        processingDays: "3-5 days",
        deliveryDays: "7-12 days",
        tracking: "Full tracking",
      },
    ],
    totalLandedCost: 98.47,
    supplier: {
      source: "cj-dropshipping",
      sku: "CAR-BRAKE-PADS-002",
      costPrice: 75.00,
      shippingDays: "5",
      shippingFee: 12.99,
      processingTime: "3-5 days",
      notes: "OEM quality ceramic formulation",
    },
  },
  {
    id: "car3",
    slug: "car-tire-pressure-monitor",
    name: "Wireless Tire Pressure Monitor",
    description: "Advanced TPMS system with real-time monitoring and smartphone app integration.",
    price: 49.99,
    compareAtPrice: 79.99,
    category: "car-parts",
    tags: ["tire", "tpms", "sensor", "safety"],
    image: "https://images.unsplash.com/photo-1563789237175-d0b3f3f2a6a8?w=500&auto=format&fit=crop&q=60",
    images: [
      "https://images.unsplash.com/photo-1563789237175-d0b3f3f2a6a8?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1620889543939-6c4a3c3b9d8e?w=500&auto=format&fit=crop&q=60",
    ],
    rating: 4.5,
    reviewCount: 67,
    createdAt: "2026-06-12",
    status: "live",
    weight: "0.8kg",
    inventory: 234,
    shippingFrom: "China",
    shippingMethods: [
      {
        name: "Standard Shipping",
        fee: 7.99,
        processingDays: "3-5 days",
        deliveryDays: "7-12 days",
        tracking: "Full tracking",
      },
    ],
    totalLandedCost: 62.48,
    supplier: {
      source: "cj-dropshipping",
      sku: "CAR-TPMS-003",
      costPrice: 55.00,
      shippingDays: "4",
      shippingFee: 7.99,
      processingTime: "3-5 days",
      notes: "Wireless 4-sensor system with app alerts",
    },
  },
  {
    id: "car4",
    slug: "car-windshield-wiper-blades",
    name: "Premium Wiper Blades Set",
    description: "Complete set of premium wiper blades for front and rear windows with aerodynamic design.",
    price: 39.99,
    compareAtPrice: 59.99,
    category: "car-parts",
    tags: ["wiper", "blade", "glass", "maintenance"],
    image: "https://images.unsplash.com/photo-1550939067-1c8f65a2a3b0?w=500&auto=format&fit=crop&q=60",
    images: [
      "https://images.unsplash.com/photo-1550939067-1c8f65a2a3b0?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1620889543939-6c4a3c3b9d8e?w=500&auto=format&fit=crop&q=60",
    ],
    rating: 4.6,
    reviewCount: 98,
    createdAt: "2026-06-08",
    status: "live",
    weight: "2.1kg",
    inventory: 167,
    shippingFrom: "China",
    shippingMethods: [
      {
        name: "Standard Shipping",
        fee: 9.99,
        processingDays: "3-5 days",
        deliveryDays: "7-12 days",
        tracking: "Full tracking",
      },
    ],
    totalLandedCost: 50.47,
    supplier: {
      source: "cj-dropshipping",
      sku: "CAR-WIPER-SET-004",
      costPrice: 45.00,
      shippingDays: "3",
      shippingFee: 9.99,
      processingTime: "3-5 days",
      notes: "All-season silicone wiper blades",
    },
  },
  {
    id: "car5",
    slug: "car-air-filter",
    name: "High-Flow Air Filter",
    description: "Performance air filter with washable design for increased airflow and engine efficiency.",
    price: 34.99,
    compareAtPrice: 49.99,
    category: "car-parts",
    tags: ["air", "filter", "performance", "engine"],
    image: "https://images.unsplash.com/photo-1620889543939-6c4a3c3b9d8e?w=500&auto=format&fit=crop&q=60",
    images: [
      "https://images.unsplash.com/photo-1620889543939-6c4a3c3b9d8e?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1550939067-1c8f65a2a3b0?w=500&auto=format&fit=crop&q=60",
    ],
    rating: 4.4,
    reviewCount: 56,
    createdAt: "2026-06-14",
    status: "live",
    weight: "1.5kg",
    inventory: 189,
    shippingFrom: "China",
    shippingMethods: [
      {
        name: "Standard shipping",
        fee: 8.99,
        processingDays: "3-5 days",
        deliveryDays: "7-12 days",
        tracking: "Full tracking",
      },
    ],
    totalLandedCost: 43.98,
    supplier: {
      source: "cj-dropshipping",
      sku: "CAR-AIR-FILTER-005",
      costPrice: 38.00,
      shippingDays: "4",
      shippingFee: 8.99,
      processingTime: "3-5 days",
      notes: "Washable foam filter for reusability",
    },
  },
];