import type { Product } from "./types";

export const cheapProducts: Product[] = [
  {
    id: "101",
    slug: "steel-wire-ball-cloth-kitchen-cleaning-dishcloth",
    name: `Steel Wire Ball Cloth Kitchen Cleaning Dishcloth`,
    description: `Product information:Pattern: PlaidColor: silver silk clothSpecifications: 20*20 [single layer], 20*20 [double layer]]Function: multifunctionalMaterial: MicrofiberApplicable object: Pot/bowlSize:Packin`,
    price: 0.18,
    compareAtPrice: 0.27,
    category: "home",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/8332ce4b-0a62-4f69-b0c3-a38d6ca16710.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD1990088",
      costPrice: 0.07,
      shippingDays: "5-10",
      shippingFee: 1.03,
      processingTime: "3-5 days",
    },
  },
  {
    id: "102",
    slug: "metal-lens-film-camera-independent-eagle-eye-protector",
    name: `Metal Lens Film Camera Independent Eagle Eye Protector`,
    description: `Product information∩╝Ücolour ∩╝Ü Hawk Eye metal iPhone 11 / 12mini / 12 (silver), Hawk Eye metal iPhone 11 / 12mini / 12 (blue), Hawk Eye metal iPhone 11 / 12mini / 12 (red), Hawk Eye metal iPhone 11 / 12`,
    price: 0.25,
    compareAtPrice: 0.38,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/1619680107524.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSJ1106046",
      costPrice: 0.1,
      shippingDays: "5-10",
      shippingFee: 1.05,
      processingTime: "3-5 days",
    },
  },
  {
    id: "103",
    slug: "cleaning-cloth-grid-oil-free-rag-kitchen-stove-dish-was",
    name: `Cleaning Cloth Grid Oil-free Rag Kitchen Stove Dish Washing Pot Cleaning Cloth`,
    description: `Product information:Pattern: solid color Color: lock silver cloth single layer, lock silver cloth double layer thickening Specification: size 20 * 20cm Function: Household Material: PVA Applicable obj`,
    price: 0.4,
    compareAtPrice: 0.6,
    category: "home",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2023/10/16/09/ee061c6e-2fcf-4fb2-a36b-ca480cdd5cfa.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD1872171",
      costPrice: 0.16,
      shippingDays: "5-10",
      shippingFee: 1.08,
      processingTime: "3-5 days",
    },
  },
  {
    id: "104",
    slug: "tempered-film-non-full-screen-hd",
    name: `Tempered Film Non-full Screen HD`,
    description: `Product information:Light transmittance: 99%Scratch resistance: 9HFilm thickness: use layer 0.26MMAdsorption: easy to suck, fast exhaust.Film characteristics: high transparency display, scratch protec`,
    price: 0.53,
    compareAtPrice: 0.8,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/15277824/15272428042785.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSJSJPB00006",
      costPrice: 0.21,
      shippingDays: "5-10",
      shippingFee: 1.11,
      processingTime: "3-5 days",
    },
  },
  {
    id: "105",
    slug: "samsung-transparent-mobile-phone-case",
    name: `Samsung transparent Mobile phone case`,
    description: `Material: tpuStyle: simpleProcess: injectionColor: transparentApplicable brand: SamsungStyle: back coverThe following is a unified display picture, take the corresponding model will send the correspon`,
    price: 0.58,
    compareAtPrice: 0.87,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/20200621/234709040883.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSJBHGA00085",
      costPrice: 0.23,
      shippingDays: "5-10",
      shippingFee: 1.12,
      processingTime: "3-5 days",
    },
  },
  {
    id: "106",
    slug: "tempered-glass-screen-protector-front-film",
    name: `Tempered Glass Screen Protector Front Film`,
    description: `Product information :Applicable products: iPhone 6, iPhone 11, iPhone 8, iPhone 7, iPhone X, iPhone 6s, iPhone Xs, iPhone 6 Plus, iPhone 6s Plus, iPhone Xr, iPhone 7 Plus, iPhone 8 Plus, iPhone Xs Max`,
    price: 0.68,
    compareAtPrice: 1.02,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/366a51ac-d97b-41f9-9a69-e8ca82008a61.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJPB1419030",
      costPrice: 0.27,
      shippingDays: "5-10",
      shippingFee: 1.14,
      processingTime: "3-5 days",
    },
  },
  {
    id: "107",
    slug: "hd-mobile-phone-film-screen-protector-tempered-glass-fi",
    name: `HD Mobile Phone Film Screen Protector Tempered Glass Film`,
    description: `Product Information:Item No.: HD PlasmaMaterial: Tempered glassFilm type: front filmFilm features: high-definition, eye protection film, scratch-resistant, anti-fingerprintColor: [HD plasma arc edge] `,
    price: 0.68,
    compareAtPrice: 1.02,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/5e95afb8-4890-453a-909e-084b33ccdc18.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJPB1329532",
      costPrice: 0.27,
      shippingDays: "5-10",
      shippingFee: 1.14,
      processingTime: "3-5 days",
    },
  },
  {
    id: "108",
    slug: "9-hole-clothes-hanger-organizer-space-saving-hanger-mul",
    name: `9-hole Clothes Hanger Organizer Space Saving Hanger Multi-function Folding Magic`,
    description: `Overview:This hanger can greatly save your wardrobe space.Dormitory and apartment for limited space.Keep your shirts, pants and shirts organized and wrinkle-free.Flexible joints at both ends for horiz`,
    price: 0.68,
    compareAtPrice: 1.02,
    category: "home",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2025/05/26/08/62fde51b-9069-4747-b82e-07a6cce3406d.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT1324319",
      costPrice: 0.27,
      shippingDays: "5-10",
      shippingFee: 1.14,
      processingTime: "3-5 days",
    },
  },
  {
    id: "109",
    slug: "multifunctional-clip-holder-thumb-hooks-wire-organizer-",
    name: `Multifunctional Clip Holder Thumb Hooks Wire Organizer Wall Hooks Hanger Strong `,
    description: `Overview:1.πÇÉSoft silicone materialπÇæThis silicone thumb wall hook is made of soft silicone material, safe and sturdy, reusable, wear-resistant, not easy to deform and fade, waterproof, anti-corrosion a`,
    price: 0.75,
    compareAtPrice: 1.13,
    category: "home",
    tags: [],
    image: "https://cf.cjdropshipping.com/210fed56-21d5-4da7-8c9a-8ef927c08b90.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT1413936",
      costPrice: 0.3,
      shippingDays: "5-10",
      shippingFee: 1.15,
      processingTime: "3-5 days",
    },
  },
  {
    id: "110",
    slug: "applicable-to-15promax-hd-rear-film-tpu-screen-protecto",
    name: `Applicable To 15promax HD Rear Film TPU Screen Protector`,
    description: `Product information:Color: rear film hydrogel film - bare chipMaterial: tempered glassSize: iPhone15, iPhone15Plus, iPhone15Pro, iPhone15ProMax, iPhone14 Pro Max, iPhone14 Plus, iPhone14Pro, iPhone14,`,
    price: 0.83,
    compareAtPrice: 1.24,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2025/05/31/06/0f47a801-dac8-4ae6-98e0-7e8d1c687a30_fine.jpeg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2389448",
      costPrice: 0.33,
      shippingDays: "5-10",
      shippingFee: 1.17,
      processingTime: "3-5 days",
    },
  },
  {
    id: "111",
    slug: "fashion-jewelry-set-zircon-gem-pendant-chain-choker-nec",
    name: `Fashion Jewelry Set Zircon Gem Pendant Chain Choker Necklace For Women Gold Colo`,
    description: `Overview:
 Unique design, stylish and beautiful.Good material, High quality.
 
 Product information:Treatment Process: Electroplating Color: gold necklace, gold stud earrings, gold ring, gold three-pi`,
    price: 0.9,
    compareAtPrice: 1.35,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/07117364-83be-4c06-899c-0a77c8e18e5e.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJLX1921850",
      costPrice: 0.36,
      shippingDays: "5-10",
      shippingFee: 1.18,
      processingTime: "3-5 days",
    },
  },
  {
    id: "112",
    slug: "compatible-withapple-suitable-forapple-12-tempered-glas",
    name: `Compatible WithApple, Suitable ForApple 12 Tempered Glass FilmIPhone11ProMax Ful`,
    description: `Note∩╝ÜNon-Apple branded products,Compatible with iPhone modelsProduct information:Applicable brand: Apple/ AppleMaterial: Tempered glassFilm type: front filmFilm characteristic`,
    price: 0.95,
    compareAtPrice: 1.42,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/1618801590036.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJPB1086305",
      costPrice: 0.38,
      shippingDays: "5-10",
      shippingFee: 1.19,
      processingTime: "3-5 days",
    },
  },
  {
    id: "113",
    slug: "household-kitchen-knife-sharpener",
    name: `Household kitchen knife sharpener`,
    description: `Size: 30.5x4cmDiameter: 0.8cmMaterial: color wood handle + carbon steelSize: 30x3.5cmDiameter: 0.8cmMaterial: 430 handle + carbon steel`,
    price: 1.03,
    compareAtPrice: 1.55,
    category: "home",
    tags: [],
    image: "https://cf.cjdropshipping.com/15954336/905202259458.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJJJTCF02180",
      costPrice: 0.41,
      shippingDays: "5-10",
      shippingFee: 1.21,
      processingTime: "3-5 days",
    },
  },
  {
    id: "114",
    slug: "kitchen-multi-function-bottle-opener-kitchen-auxiliary-",
    name: `Kitchen Multi-function Bottle Opener Kitchen Auxiliary Scissors`,
    description: `Product information:Color: Orange Gray Specification: about 21.5 * 8.3cm Material: PP stainless steel
 
 Packing list: 
 1*Kitchen Scissors
 
 
 Product Image:
 
 
 
 
 
 
 
 
 
 
 
 
 `,
    price: 1.2,
    compareAtPrice: 1.8,
    category: "home",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/cd9cae08-b33d-42a7-a9f4-c9fc90901387.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD1975246",
      costPrice: 0.48,
      shippingDays: "5-10",
      shippingFee: 1.24,
      processingTime: "3-5 days",
    },
  },
  {
    id: "115",
    slug: "nylon-strainer-large-scoop-colander-kitchen-appliances-",
    name: `Nylon Strainer Large Scoop Colander Kitchen Appliances Spoon Shovel Soup Spoon F`,
    description: `Overview:Scoop and drain food straight from the oven or out of the pan.Perfect for frying food or the food in&`,
    price: 1.2,
    compareAtPrice: 1.8,
    category: "home",
    tags: [],
    image: "https://cf.cjdropshipping.com/20200712/1330191651015.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJJJTCF02021",
      costPrice: 0.48,
      shippingDays: "5-10",
      shippingFee: 1.24,
      processingTime: "3-5 days",
    },
  },
  {
    id: "116",
    slug: "magnetic-silicone-case-for-liquid-silicone-magnetic-pho",
    name: `Magnetic Silicone Case For Liquid Silicone Magnetic Phone Case`,
    description: `Product information:Applicable brand: AppleStyle: back coverMaterial: SiliconeStyle: simplePopular elements: pure colorProcess: injection molding/injectioncolour:	Red, blue, black, rose red, orange, d`,
    price: 1.25,
    compareAtPrice: 1.88,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/9565d91a-0e4d-4dd0-a45e-f7f64490eb25.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJGJ1208466",
      costPrice: 0.5,
      shippingDays: "5-10",
      shippingFee: 1.25,
      processingTime: "3-5 days",
    },
  },
  {
    id: "117",
    slug: "lens-protector-ar-enhanced-silk-screen-black-ring",
    name: `Lens Protector AR Enhanced Silk Screen Black Ring`,
    description: `Product information:Color: large Arc HD lens protector (hole) Material: tempered glass Size: OnePlus 12, find N3,OnePlus 11 Screen protector features: HD, explosion-proof, dustproof, fingerprint-proof`,
    price: 1.25,
    compareAtPrice: 1.88,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/05/26/02/d10fa1c4-de95-4a92-a93d-0408c411b542.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2045957",
      costPrice: 0.5,
      shippingDays: "5-10",
      shippingFee: 1.25,
      processingTime: "3-5 days",
    },
  },
  {
    id: "118",
    slug: "transparent-magnetic-acrylic-phone-case",
    name: `Transparent Magnetic Acrylic Phone Case`,
    description: `Product information:Color: generation magnetic suction shell [big hole]]Applicable model: AppleFunction: shockproof, heat dissipation, magnetic suction, anti-wear, anti-fall, anti-fingerprintMaterial:`,
    price: 1.33,
    compareAtPrice: 2,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/d7fafb63-2f34-4371-94c4-9bc0428c7e1d.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT2151360",
      costPrice: 0.53,
      shippingDays: "5-10",
      shippingFee: 1.27,
      processingTime: "3-5 days",
    },
  },
  {
    id: "119",
    slug: "stylish-and-simple-acrylic-phone-case",
    name: `Stylish And Simple Acrylic Phone Case`,
    description: `Product Information:Style: All InclusiveMaterial: AcrylicColor: Black, Pink, Purple, Sky Blue, Green, WhiteModel: iPhone 14, iPhone 14Pro, iPhone 14PROMAX, iPhone 14PLUS, iPhone 13, iPhone 13PRO, iPho`,
    price: 1.33,
    compareAtPrice: 2,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/ba129b63-11d7-4d86-98d0-88608dfde683.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJPG1714115",
      costPrice: 0.53,
      shippingDays: "5-10",
      shippingFee: 1.27,
      processingTime: "3-5 days",
    },
  },
  {
    id: "120",
    slug: "5pcs-fashion-butterfly-pendants-necklace-earrings-ring-",
    name: `5PCS Fashion Butterfly Pendants Necklace Earrings Ring Bracelet Sets For Women J`,
    description: `
 Overview:
 Simple style, showing temperament.
 It can be used for daily commuting and going out on the street.
 It can be used as a fashionable matching item whether you qre shopping or dating.
 Use`,
    price: 1.33,
    compareAtPrice: 2,
    category: "style",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/06/14/06/7a7932ed-ec31-4f42-98a2-030d64751973.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJLX2038493",
      costPrice: 0.53,
      shippingDays: "5-10",
      shippingFee: 1.27,
      processingTime: "3-5 days",
    },
  },
  {
    id: "121",
    slug: "silicone-phone-case",
    name: `Silicone phone case`,
    description: `MMaterial: SiliconeColor: wine red,  light blue, grey, dark green, begonia, rose gold, bean green, black, `,
    price: 1.4,
    compareAtPrice: 2.1,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/20200630/6177185475989.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSJBHIP00866",
      costPrice: 0.56,
      shippingDays: "5-10",
      shippingFee: 1.28,
      processingTime: "3-5 days",
    },
  },
  {
    id: "122",
    slug: "lens-protector-tempered-glass-integrated-camera-protect",
    name: `Lens Protector Tempered Glass Integrated Camera Protective Film`,
    description: `Product information:Material: Tempered glassFilm type: rear filmFilm features: high-definition, explosion-proof, dustproof, fingerprint proof, and anti dropNon-Apple brand products, compatible with IP`,
    price: 1.4,
    compareAtPrice: 2.1,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/d42af70b-4284-4f21-9028-a4f216ea88f4.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2002653",
      costPrice: 0.56,
      shippingDays: "5-10",
      shippingFee: 1.28,
      processingTime: "3-5 days",
    },
  },
  {
    id: "123",
    slug: "kitchen-household-high-pressure-glass-spray-bottle",
    name: `Kitchen Household High-pressure Glass Spray Bottle`,
    description: `Product information:Function: oil injection Material: Glass Capacity: 100ml-plastic pink, 100ml-plastic blue, 100ml-silver plated, 100ml-gold plated, 100ml-rose gold platedPacking list: Oil Dispenser `,
    price: 1.4,
    compareAtPrice: 2.1,
    category: "home",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/01/05/12/d99f6467-429b-4fa3-a380-853c5ebfe80c_trans.jpeg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD1940656",
      costPrice: 0.56,
      shippingDays: "5-10",
      shippingFee: 1.28,
      processingTime: "3-5 days",
    },
  },
  {
    id: "124",
    slug: "aluminum-alloy-lens-protector-15plus-hollow-15-camera-p",
    name: `Aluminum Alloy Lens Protector 15plus Hollow 15 Camera Protection Ring Frame`,
    description: `Product information:Color: Antifreeze bag, small square box, high-end integrated paper box Material: aluminum alloy Screen protector function: anti-frost, HD, color film, explosion-proof, dustproof, a`,
    price: 1.43,
    compareAtPrice: 2.15,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/d8bded1b-80a2-4dbf-ba69-aa4137a45eff.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2005599",
      costPrice: 0.57,
      shippingDays: "5-10",
      shippingFee: 1.29,
      processingTime: "3-5 days",
    },
  },
  {
    id: "125",
    slug: "pattern-kitchen-knife",
    name: `Pattern Kitchen Knife`,
    description: `
 Overview:We imported 67 layers of Damascus steel chef's knife from Japan. This is a multi-functional professional kitchen Damascus knife with a durable blade that can perfectly cut, cut, slice and d`,
    price: 1.45,
    compareAtPrice: 2.17,
    category: "home",
    tags: [],
    image: "https://cf.cjdropshipping.com/15688224/89196272316.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJJCFCF00514",
      costPrice: 0.58,
      shippingDays: "5-10",
      shippingFee: 1.29,
      processingTime: "3-5 days",
    },
  },
  {
    id: "126",
    slug: "frosted-all-inclusive-mobile-phone-case",
    name: `Frosted All-Inclusive Mobile Phone Case`,
    description: `Product information:Style: back coverMaterial: tpuStyle: SimplePopular elements: solid colorColor: brown, wine red, bean green, black, green, grey, rose gold, light blue, light pink, orange, yellow, o`,
    price: 1.48,
    compareAtPrice: 2.22,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/1615959755932.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJIP1045144",
      costPrice: 0.59,
      shippingDays: "5-10",
      shippingFee: 1.3,
      processingTime: "3-5 days",
    },
  },
  {
    id: "127",
    slug: "screen-printing-3d-radian-lens-protection-film",
    name: `Screen Printing 3D Radian Lens Protection Film`,
    description: `Product information:Material: tempered glassFilm type: front filmFilm features: HD, explosion-proof, anti-fingerprint, automatic repairColor:black luminous ring /1 piece of installation,Size: iPhone14`,
    price: 1.48,
    compareAtPrice: 2.22,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/207d0fd6-a424-4b3b-b182-c3f1efb52b87.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSJ1649497",
      costPrice: 0.59,
      shippingDays: "5-10",
      shippingFee: 1.3,
      processingTime: "3-5 days",
    },
  },
  {
    id: "128",
    slug: "home-with-net-spong-mop-kitchen-decontamination-cleanin",
    name: `Home With Net Spong Mop Kitchen Decontamination Cleaning Brush`,
    description: `Product information:Color: 5 color chip Material: sponge Application object: Pot/bowl
 
 Packing list: 
 5pcs / 20pcs Cleaning Brushs
 
 
 Product Image:
 
 
 
 
 
 
 
 `,
    price: 1.48,
    compareAtPrice: 2.22,
    category: "home",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/2421fb9d-e321-440d-8694-7dff90f8eb9a.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2052046",
      costPrice: 0.59,
      shippingDays: "5-10",
      shippingFee: 1.3,
      processingTime: "3-5 days",
    },
  },
  {
    id: "129",
    slug: "hand-painted-love-phone-case",
    name: `Hand painted love phone case`,
    description: `Style: back coverMaterial: tpuStyle: simplePopular elements: loveMaterial: TPU matte feel, all-inclusive silicone soft shellWith lanyard holes on the sidesProcess: bronzing processStyle: Japanese and `,
    price: 1.5,
    compareAtPrice: 2.25,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/20200913/1143112743762.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSJBHIP01243",
      costPrice: 0.6,
      shippingDays: "5-10",
      shippingFee: 1.3,
      processingTime: "3-5 days",
    },
  },
  {
    id: "130",
    slug: "all-inclusive-silicone-phone-case",
    name: `All-inclusive Silicone Phone Case`,
    description: `Product information:Applicable brand: AppleStyle: all-inclusiveMaterial: imitation leatherStyle: Chinese stylePopular elements: stripes, letters, geometryProcess: metal stampingColor: wavy texture - a`,
    price: 1.5,
    compareAtPrice: 2.25,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/c7949758-e791-48b1-83c5-7180455c0f81.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJPG1673875",
      costPrice: 0.6,
      shippingDays: "5-10",
      shippingFee: 1.3,
      processingTime: "3-5 days",
    },
  },
  {
    id: "131",
    slug: "applicable-to-y20-full-screen-tempered-protective-film-",
    name: `Applicable To Y20 Full Screen Tempered Protective Film Set`,
    description: `Product information:Color: vivo Y20 two strong full Glue black ribbon packaging Material: tempered glass Screen protector features: HD, anti-fingerprint, 7323209Packing list: Tempered film * 1 setProd`,
    price: 1.5,
    compareAtPrice: 2.25,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/08/28/05/3937c114-039f-4ba7-89de-f960d8323cdf_fine.jpeg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2121990",
      costPrice: 0.6,
      shippingDays: "5-10",
      shippingFee: 1.3,
      processingTime: "3-5 days",
    },
  },
  {
    id: "132",
    slug: "simple-love-jewelry-women-s-fashion-necklace-suit-heart",
    name: `Simple Love Jewelry Women's Fashion Necklace Suit Heart Jewelry Set Gift For Her`,
    description: `Overview:Simple style, showing temperament.It can be used for daily commuting and going out on the street.Whether shopping&nb`,
    price: 1.5,
    compareAtPrice: 2.25,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/be957a42-7587-4dd0-9c3e-70ebaa4b130a.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJLX2086066",
      costPrice: 0.6,
      shippingDays: "5-10",
      shippingFee: 1.3,
      processingTime: "3-5 days",
    },
  },
  {
    id: "133",
    slug: "dark-purple-phone-case-liquid-silicone",
    name: `Dark Purple Phone Case Liquid Silicone`,
    description: `Product information:Color classification: [Klein blue] Pupil, [wine red] Pupil, [far peak Blue] Pupil, [Dark Night Purple] Pupil, [cangling Green] Pupil, [classic black] Pupil, [Plaster White] Pupil, `,
    price: 1.53,
    compareAtPrice: 2.3,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/2abfb6a1-1aac-4eae-8826-919ff95b6e64.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT2249881",
      costPrice: 0.61,
      shippingDays: "5-10",
      shippingFee: 1.31,
      processingTime: "3-5 days",
    },
  },
  {
    id: "134",
    slug: "simple-and-advanced-woven-phone-case",
    name: `Simple And Advanced Woven Phone Case`,
    description: `Overview:Note∩╝ÜNon-Apple brand products,Applicable to iPhone models.Specification:Style: All InclusiveMaterial: Liquid siliconePopular element: Wave patternColors: Black, green, pink, white, yello`,
    price: 1.55,
    compareAtPrice: 2.33,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/5a96db98-b919-4430-8bb8-bdfeaf79ac8c.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJFG1761844",
      costPrice: 0.62,
      shippingDays: "5-10",
      shippingFee: 1.31,
      processingTime: "3-5 days",
    },
  },
  {
    id: "135",
    slug: "kitchen-gadget-dovetail-fruit-and-vegetable-knife-kitch",
    name: `Kitchen Gadget Dovetail Fruit And Vegetable Knife Kitchen Modeling Tool Carving`,
    description: `Product information:Specifications: knife, knife spring Material: 2cr14 stainless steel PP new material handle Style: modern simplicity
 
 Size:
 
 
 
 
 
  Packing list: 
  Knife *1/Knife *1+Spring*1`,
    price: 1.55,
    compareAtPrice: 2.33,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/0981f385-29ab-4636-a6e1-118af725b7c7.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD1971037",
      costPrice: 0.62,
      shippingDays: "5-10",
      shippingFee: 1.31,
      processingTime: "3-5 days",
    },
  },
  {
    id: "136",
    slug: "cute-santa-claus-phone-case-frosted-advanced-christmas-",
    name: `Cute Santa Claus Phone Case Frosted Advanced Christmas Pattern Case For Phone Sh`,
    description: `Overview:It is made of soft and durable PU leather (one kind of faux leather). Zippers are smooth enough and&n`,
    price: 1.58,
    compareAtPrice: 2.37,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/920ea9f8-5221-43ab-94c0-621693289928.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT2197473",
      costPrice: 0.63,
      shippingDays: "5-10",
      shippingFee: 1.32,
      processingTime: "3-5 days",
    },
  },
  {
    id: "137",
    slug: "compatible-with-tempered-glass-screen-protector-for-11-",
    name: `Compatible With Tempered Glass Screen Protector For   11 Pro Max 12 Mini 11Pro 1`,
    description: `Note∩╝ÜNon-Apple branded products,Compatible with iPhone modelsSpecification:Applicable brand: Apple/ appleMaterial: Tempered glassFilm type: Front filmFilm features: High-defin`,
    price: 1.58,
    compareAtPrice: 2.37,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2025/07/21/06/fe04e9c2-8c73-4251-a0fe-f3f4ad0963d5.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJPB1038133",
      costPrice: 0.63,
      shippingDays: "5-10",
      shippingFee: 1.32,
      processingTime: "3-5 days",
    },
  },
  {
    id: "138",
    slug: "black-striped-pupil-phone-case",
    name: `Black Striped Pupil Phone Case`,
    description: `Product information:Color: Black pupil-KT200 black stripes Material: tpu Style: Back cover type Style: Japan and South Korea, Europe and America Applicable models: iPhone 11,iPhone 12,iPhone 8,iPhone `,
    price: 1.6,
    compareAtPrice: 2.4,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/05/29/09/82571cba-b8b2-4669-86a3-f94c67236306.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT2046951",
      costPrice: 0.64,
      shippingDays: "5-10",
      shippingFee: 1.32,
      processingTime: "3-5 days",
    },
  },
  {
    id: "139",
    slug: "hd-tempered-glass-integrated-camera-lens-protector",
    name: `HD Tempered Glass Integrated Camera Lens Protector`,
    description: `Product information:Color: flash transparent integration [silver], flash transparent integration [Purple], flash transparent integration [colorful color], flash transparent integration [gold], flash t`,
    price: 1.6,
    compareAtPrice: 2.4,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/4a057e27-8623-4454-9c97-a6f6e09d2421.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2017110",
      costPrice: 0.64,
      shippingDays: "5-10",
      shippingFee: 1.32,
      processingTime: "3-5 days",
    },
  },
  {
    id: "140",
    slug: "fashion-women-s-metal-bead-necklace-pendant-earrings-je",
    name: `Fashion Women's Metal Bead Necklace Pendant Earrings Jewelry Set`,
    description: ``,
    price: 1.6,
    compareAtPrice: 2.4,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/172ae511-6160-448f-bab3-8a1b225f419e.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJST2635821",
      costPrice: 0.64,
      shippingDays: "5-10",
      shippingFee: 1.32,
      processingTime: "3-5 days",
    },
  },
  {
    id: "141",
    slug: "new-angel-elf-earrings-necklace-bracelet-three-piece-au",
    name: `New Angel Elf Earrings Necklace Bracelet Three-piece Austria Crystal Alloy Jewel`,
    description: `Style: Europe and America Material: Alloy Process: crystal Set combination: earrings + accessories + jewelry`,
    price: 1.6,
    compareAtPrice: 2.4,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/20180818/1220584059723.png",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJZBGJZB00019",
      costPrice: 0.64,
      shippingDays: "5-10",
      shippingFee: 1.32,
      processingTime: "3-5 days",
    },
  },
  {
    id: "142",
    slug: "protein-powder-container-portable-fitness-pill-box-orga",
    name: `Protein Powder Container Portable Fitness Pill Box Organizer`,
    description: `Product information:Pattern: Solid color Material: PP Packaging Specification: Single piece Structure: Single layer Shape: Round External Dimensions (Height, Diameter): 8.8*7.2Packing list: Storage bo`,
    price: 1.63,
    compareAtPrice: 2.44,
    category: "home",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2026/03/20/08/1ded18b2-7c62-44ba-a8d4-750da1b40a65_fine.jpeg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2796364",
      costPrice: 0.65,
      shippingDays: "5-10",
      shippingFee: 1.33,
      processingTime: "3-5 days",
    },
  },
  {
    id: "143",
    slug: "cream-pattern-mirror-phone-case-drop-resistant-transpar",
    name: `Cream Pattern Mirror Phone Case Drop-resistant Transparent Case`,
    description: `Product information:Overview:Non Apple branded products,Compatible with iPhone models.Color: [black cream pattern] Mirror, [white cream pattern] Mirror, [transparent cream pattern] Mirror Material: tp`,
    price: 1.65,
    compareAtPrice: 2.47,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/27d191a5-cb80-41d4-8fe4-77d4b9b75a6b.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT1989552",
      costPrice: 0.66,
      shippingDays: "5-10",
      shippingFee: 1.33,
      processingTime: "3-5 days",
    },
  },
  {
    id: "144",
    slug: "press-type-convenient-outdoor-portable-ice-tray-large-c",
    name: `Press-type Convenient Outdoor Portable Ice Tray Large Capacity Ice Bucket 48 Ext`,
    description: `Overview:Easy to release: This ice cube tray has a push type of quick release ice. Simply pour the ice tray onto the refrigerator, cover it with a lid, and press the place button on the ice tray to qu`,
    price: 1.65,
    compareAtPrice: 2.47,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2025/04/07/07/8828d7e0-2b97-4a55-96c2-a0846ae244ce.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2333076",
      costPrice: 0.66,
      shippingDays: "5-10",
      shippingFee: 1.33,
      processingTime: "3-5 days",
    },
  },
  {
    id: "145",
    slug: "mobile-phone-repair-blasting-pen-broken-glass-artifact-",
    name: `Mobile Phone Repair Blasting Pen Broken Glass Artifact Adjustable Strength Broke`,
    description: `Product information:Material: Plastic, alloyWeight: About 33gPen Size:16.7*16.7*115mmPacking list:Mobile Phone Repair Tools*1 Set`,
    price: 1.68,
    compareAtPrice: 2.52,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/b37107ed-f3e0-430b-9051-a731feb9687e.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSI1664176",
      costPrice: 0.67,
      shippingDays: "5-10",
      shippingFee: 1.34,
      processingTime: "3-5 days",
    },
  },
  {
    id: "146",
    slug: "faucet-splashproof-kitchen-home-shower-universal-joint-",
    name: `Faucet Splashproof Kitchen Home Shower Universal Joint Extender`,
    description: `
 Product information:
 Surface treatment: electroplatingControl method: single handle single controlMaterial: plasticNominal pressure: 0.1-0.4 (Mpa)Working temperature: 0-65 (Γäâ)Specifications: short `,
    price: 1.7,
    compareAtPrice: 2.55,
    category: "home",
    tags: [],
    image: "https://cf.cjdropshipping.com/a118805a-fd04-4360-a53d-09abfb1ce6ac.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJCF1574172",
      costPrice: 0.68,
      shippingDays: "5-10",
      shippingFee: 1.34,
      processingTime: "3-5 days",
    },
  },
  {
    id: "147",
    slug: "frosted-silicone-phone-case",
    name: `Frosted Silicone Phone Case`,
    description: `Material: Silicone`,
    price: 1.73,
    compareAtPrice: 2.6,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/20200529/1588019609101.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSJYDSJ00122",
      costPrice: 0.69,
      shippingDays: "5-10",
      shippingFee: 1.35,
      processingTime: "3-5 days",
    },
  },
  {
    id: "148",
    slug: "mother-s-day-jewelry-set-stainless-steel-i-love-mom-mam",
    name: `Mother's Day Jewelry Set Stainless Steel I Love Mom Mama Love Heart Pendant Neck`,
    description: `
 Overview:
 Material Alloy, Fashion Style, Unleaded, , Don't Have To Punch, Directly To Wear, Simple,statement And Special.
 This Necklace Earrings Bracelet Set Can Pair With Different Styles Of Acce`,
    price: 1.73,
    compareAtPrice: 2.6,
    category: "style",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/03/14/05/06771c0d-4de5-42c2-bfb8-489273e9e14b.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJLX1986695",
      costPrice: 0.69,
      shippingDays: "5-10",
      shippingFee: 1.35,
      processingTime: "3-5 days",
    },
  },
  {
    id: "149",
    slug: "korean-vintage-floral-phone-case",
    name: `Korean Vintage Floral Phone Case`,
    description: `Product information:Color: green-blue pollen rose, embroidered green flower purple rose, white flower Purple Rose Applicable model: Apple Function: Fall Protection Material: tpu Color classification: `,
    price: 1.75,
    compareAtPrice: 2.63,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/d2e7be13-d9c1-4b1a-adbd-275e06062b6c.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT2066584",
      costPrice: 0.7,
      shippingDays: "5-10",
      shippingFee: 1.35,
      processingTime: "3-5 days",
    },
  },
  {
    id: "150",
    slug: "transparent-fluorescent-color-tpu-phone-case",
    name: `Transparent Fluorescent Color TPU Phone Case`,
    description: `Product information:Color: dark blue fluorescent TPU, orange fluorescent TPU, dark purple fluorescent TPU, yellow fluorescent TPU, rose fluorescent TPU, light purple fluorescent TPU Applicable model: `,
    price: 1.75,
    compareAtPrice: 2.63,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/06/27/03/c679ccbf-9a1b-4cfe-8c9c-5304dc53be6f.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT2069460",
      costPrice: 0.7,
      shippingDays: "5-10",
      shippingFee: 1.35,
      processingTime: "3-5 days",
    },
  },
  {
    id: "151",
    slug: "bride-rhinestone-pearl-earrings-necklace-set-banquet-dr",
    name: `Bride Rhinestone Pearl Earrings Necklace Set Banquet Dress Jewelry`,
    description: `Product information:Style: Europe and AmericaMaterial: AlloyTreatment process: pearlBrand: Sui change jewelryType: NecklaceStyle: Women'sModeling: geometricPackaging: Individually packed	Chain style: `,
    price: 1.75,
    compareAtPrice: 2.63,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/15097248/3218588636_1297013011.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJZBHLXN00308",
      costPrice: 0.7,
      shippingDays: "5-10",
      shippingFee: 1.35,
      processingTime: "3-5 days",
    },
  },
  {
    id: "152",
    slug: "all-inclusive-frosted-tpu-phone-case",
    name: `All-inclusive Frosted TPU Phone Case`,
    description: `
 Product information:Color: TPU Black, Applicable brand: Huawei Material: tpu Popular elements: solid color Style: Back cover type Style: Simple Process: Injection Molding/ Note:Non-Huawei brand prod`,
    price: 1.8,
    compareAtPrice: 2.7,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/40b0fa0c-1dea-40a9-92f5-d0d6df4528e9.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT1577062",
      costPrice: 0.72,
      shippingDays: "5-10",
      shippingFee: 1.36,
      processingTime: "3-5 days",
    },
  },
  {
    id: "153",
    slug: "fluorescent-tempered-glass-film-full-screen",
    name: `Fluorescent Tempered Glass Film Full Screen`,
    description: `Product information:Applicable brands: Apple/AppleMaterial: Tempered glassFilm type: Front filmFilm features: Luminous, high-definitionProcess: MachiningColor: Pink luminous [HD bare film], yello`,
    price: 1.85,
    compareAtPrice: 2.78,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/d28b91f4-bcbe-4e9c-aba2-244cacaf6c9a.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJPB1482707",
      costPrice: 0.74,
      shippingDays: "5-10",
      shippingFee: 1.37,
      processingTime: "3-5 days",
    },
  },
  {
    id: "154",
    slug: "frosted-frame-lens-phone-case",
    name: `Frosted frame lens phone case`,
    description: `Material SiliconeStyle simplePopular elements Pure color`,
    price: 1.88,
    compareAtPrice: 2.82,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/20200903/1156307145557.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSJBHIP01190",
      costPrice: 0.75,
      shippingDays: "5-10",
      shippingFee: 1.38,
      processingTime: "3-5 days",
    },
  },
  {
    id: "155",
    slug: "creative-noodle-potentiometer-pasta-measurer-noodle-mak",
    name: `Creative Noodle Potentiometer Pasta Measurer Noodle Maker Selector Measurer Kitc`,
    description: `Overview:Creative Plastic Spaghetti Measuring ToolYou can control the thickness of the noodles according to your preferencesproduct information:Kitchen toolsPasta measuring toolConvenient, compact and`,
    price: 1.88,
    compareAtPrice: 2.82,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/15605280/352925190104.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJJJTCF00671",
      costPrice: 0.75,
      shippingDays: "5-10",
      shippingFee: 1.38,
      processingTime: "3-5 days",
    },
  },
  {
    id: "156",
    slug: "liquid-silicone-mobile-phone-case",
    name: `Liquid silicone mobile phone case`,
    description: `Applicable brand: SamsungStyle: back coverMaterial: silica gelStyle: luxury`,
    price: 1.9,
    compareAtPrice: 2.85,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/2053/4138804733740.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSJBHGA00163",
      costPrice: 0.76,
      shippingDays: "5-10",
      shippingFee: 1.38,
      processingTime: "3-5 days",
    },
  },
  {
    id: "157",
    slug: "bohemian-metal-chain-bracelet-set-for-women-geometric-g",
    name: `Bohemian Metal Chain Bracelet Set For Women Geometric Gold Color Thick Link Chai`,
    description: `
 Overview:
 Unique design, stylish and beautiful.Good material, High quality.
 
 Product information:Color: AR-0752 Material: Alloy Popular elements: irregular, musical note, chain
 
 Packing list: 
`,
    price: 1.93,
    compareAtPrice: 2.9,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/82bec096-8336-462b-9c0d-df96d8a72ad4.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSL2008483",
      costPrice: 0.77,
      shippingDays: "5-10",
      shippingFee: 1.39,
      processingTime: "3-5 days",
    },
  },
  {
    id: "158",
    slug: "multifunctional-slotted-spoon-grinding-cooking-spoon-ma",
    name: `Multifunctional Slotted Spoon Grinding Cooking Spoon Mashed Auxiliary Food Ginge`,
    description: `Overview:Creative multifunctional cooking spoonFood-grade material, high temperature resistance, safe and environmentally friendly, can be used for cooking, draining spoon, grinding, pressing mud and `,
    price: 1.95,
    compareAtPrice: 2.93,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/08/26/07/79350ee1-7117-43b5-805b-554f58210351.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJJJTCF01196",
      costPrice: 0.78,
      shippingDays: "5-10",
      shippingFee: 1.39,
      processingTime: "3-5 days",
    },
  },
  {
    id: "159",
    slug: "peeler-kitchen-multi-functional-household",
    name: `Peeler Kitchen Multi-functional Household`,
    description: `Product information:Specification: zinc alloy peeler-primary color, zinc alloy peeler-GoldApplicable occasions for gifts: all placesMaterial: zinc alloy stainless steel 420 bladeStyle: comfortable
 
 `,
    price: 1.95,
    compareAtPrice: 2.93,
    category: "home",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/aba9bfe2-c270-432b-83be-5fa8eb6778d3.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2072968",
      costPrice: 0.78,
      shippingDays: "5-10",
      shippingFee: 1.39,
      processingTime: "3-5 days",
    },
  },
  {
    id: "160",
    slug: "fashion-jewelry-4-pcs-crystal-bracelet-set-bohemian-des",
    name: `Fashion Jewelry 4 Pcs Crystal Bracelet Set Bohemian Design For Women Vintage Lux`,
    description: `
 Overview:
 4Pcs Bracelets: This set of women's bracelets includes different styles of bracelets: Fried Dough Twists bracelets, punk gem bracelets, square crystal bracelets open crystal bracelets and`,
    price: 1.98,
    compareAtPrice: 2.97,
    category: "style",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/02/26/05/90316e5b-599e-4400-b79d-41e313dcab78.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSL1961619",
      costPrice: 0.79,
      shippingDays: "5-10",
      shippingFee: 1.4,
      processingTime: "3-5 days",
    },
  },
  {
    id: "161",
    slug: "laser-gradient-transparent-frosted-phone-case",
    name: `Laser Gradient Transparent Frosted Phone Case`,
    description: `Product information:Color: XYM two-in-one laser gradient transparent Function: Anti-fall and anti-fingerprint Material: tpu Color classification: color matching Applicable models: iPhone 11,iPhone 12,`,
    price: 2,
    compareAtPrice: 3,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/c895c3c4-7893-49aa-aa23-5262e9612a65.jpg?bid=2408150136271949200",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT1796745",
      costPrice: 0.8,
      shippingDays: "5-10",
      shippingFee: 1.4,
      processingTime: "3-5 days",
    },
  },
  {
    id: "162",
    slug: "lens-integrated-glass-protector-protection",
    name: `Lens Integrated Glass Protector Protection`,
    description: `
 Product information:Color: Xiaomi 14U black edge, Xiaomi 14U black Golden EdgeMaterial: ordinary filmScreen protector feature: Frosted, explosion-proof, drop-proofApplicable model: Xiaomi
 
 Packing`,
    price: 2,
    compareAtPrice: 3,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/10/22/06/c9d55592-158d-4498-ba86-70877a5cadfd_trans.jpeg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2167590",
      costPrice: 0.8,
      shippingDays: "5-10",
      shippingFee: 1.4,
      processingTime: "3-5 days",
    },
  },
  {
    id: "163",
    slug: "stainless-steel-hand-hammered-tone-boning-knife-househo",
    name: `Stainless Steel Hand Hammered Tone Boning Knife Household Kitchen`,
    description: `Product information:Specifications: Huanghua pear bone sharpener, walnut bone sharpener, black bone sharpener, 3.0 thick sand bone sharpener, leather case Style: modern simplicity Process: Hammer grai`,
    price: 2,
    compareAtPrice: 3,
    category: "home",
    tags: [],
    image: "https://cf.cjdropshipping.com/a0137f67-c677-4402-9c73-8ff7f0cd2c1a.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJCF1777518",
      costPrice: 0.8,
      shippingDays: "5-10",
      shippingFee: 1.4,
      processingTime: "3-5 days",
    },
  },
  {
    id: "164",
    slug: "fashion-blue-luminous-butterfly-necklace-bracelet-set-f",
    name: `Fashion Blue Luminous Butterfly Necklace Bracelet Set For Glow In The Dark Women`,
    description: `Overview:Use Occasion: As a gift for women - Perfect Anniversary gift or Birthday gift for Mom, daughter, Granddaug`,
    price: 2.1,
    compareAtPrice: 3.15,
    category: "style",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/12/19/06/e654478a-061f-4dfe-97a4-7bcc08a1f0f1.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJLX2189288",
      costPrice: 0.84,
      shippingDays: "5-10",
      shippingFee: 1.42,
      processingTime: "3-5 days",
    },
  },
  {
    id: "165",
    slug: "european-and-american-jewelry-bride-pearl-crystal-with-",
    name: `European And American Jewelry Bride Pearl Crystal With Short Collarbone Neck Nec`,
    description: `Product Information:Style: European and AmericanMaterial: AlloyTreatment process: electroplatingType: pendant, pendantStyle: Women'sShape: drop shapeChain style: round bead chainCircumference: 21cm (i`,
    price: 2.1,
    compareAtPrice: 3.15,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/1618313907789.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJZB1078673",
      costPrice: 0.84,
      shippingDays: "5-10",
      shippingFee: 1.42,
      processingTime: "3-5 days",
    },
  },
  {
    id: "166",
    slug: "fashion-jewelry-silver-color-butterfly-rings-for-women-",
    name: `Fashion Jewelry Silver Color Butterfly Rings For Women Men Lover Vintage Geometr`,
    description: `
 Overview:
 Unique design, stylish and beautiful.Good material, High quality.
 
 Product information:Type: Ring Treatment Process: Diamond Color: HS1397 Applicable population: Female Material: Alloy `,
    price: 2.13,
    compareAtPrice: 3.2,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/0bcc7002-45e1-4e88-aecb-edb09075aadd.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJLX2017184",
      costPrice: 0.85,
      shippingDays: "5-10",
      shippingFee: 1.43,
      processingTime: "3-5 days",
    },
  },
  {
    id: "167",
    slug: "silver-electroplated-cream-grain-phone-case",
    name: `Silver Electroplated Cream Grain Phone Case`,
    description: `Product information:Color: silver-plated cream color Function: Fall Protection Material: Silicone Color classification: white, black, transparent Popular elements: Bracelet Style: all-inclusive Applic`,
    price: 2.15,
    compareAtPrice: 3.22,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/dbcff404-f559-4280-8b34-3c2f530d07ec.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT1844908",
      costPrice: 0.86,
      shippingDays: "5-10",
      shippingFee: 1.43,
      processingTime: "3-5 days",
    },
  },
  {
    id: "168",
    slug: "cup-slicers-fruit-slicers-egg-slicers-stainless-steel-s",
    name: `Cup Slicers Fruit Slicers Egg Slicers Stainless Steel Strawberry Slicers Banana `,
    description: `
 Overview:
 πÇÉCompletely HarmlessπÇæFruit cutter cup is smooth and burr-free, which will not hurt your hands. The cup design keeps hands away from the blades for added safety.πÇÉEasy UsageπÇæThe cup cutter `,
    price: 2.15,
    compareAtPrice: 3.22,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/01/02/09/3c0318b0-3bac-4995-bc84-80eb7da5dd77.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJCF1836236",
      costPrice: 0.86,
      shippingDays: "5-10",
      shippingFee: 1.43,
      processingTime: "3-5 days",
    },
  },
  {
    id: "169",
    slug: "factory-supply-kitchen-hook-rack-punch-free-wall-mounte",
    name: `Factory Supply Kitchen Hook Rack Punch-free Wall-mounted Rack Aerospace Aluminum`,
    description: `Product information:Treatment Process: anodic oxidationSpecifications: good-looking [light luxury] gun gray with 4 hooks, good-looking [light luxury] gun gray with 6 hooks, good-looking [light luxury]`,
    price: 2.15,
    compareAtPrice: 3.22,
    category: "home",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/f18b8592-bf2b-49e8-ba01-4c007ece0052.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2069721",
      costPrice: 0.86,
      shippingDays: "5-10",
      shippingFee: 1.43,
      processingTime: "3-5 days",
    },
  },
  {
    id: "170",
    slug: "4pcs-set-bohemian-woven-rope-foot-chain-for-men-and-wom",
    name: `4pcs Set Bohemian Woven Rope Foot Chain For Men And Women Geometric Alloy Black `,
    description: `Overview:Unique design, stylish and beautiful.Good material, High quality.100% Brand New.Product information:Material: alloyModeling: geometric typeColor: Style21255Packing list:Ankle *1`,
    price: 2.15,
    compareAtPrice: 3.22,
    category: "style",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2025/02/26/01/6eebc7f7-b910-4394-9c62-1e87c045d493.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJST2307851",
      costPrice: 0.86,
      shippingDays: "5-10",
      shippingFee: 1.43,
      processingTime: "3-5 days",
    },
  },
  {
    id: "171",
    slug: "4pcs-set-simple-white-faux-pearls-beads-beaded-heart-te",
    name: `4pcs Set Simple White Faux Pearls Beads Beaded Heart Temperament Bracelet Set El`,
    description: `Overview:Unique design, stylish and beautiful.Good material, High quality.100% Brand New.

Product information:Type: Bracelet Color: S1412-3,S1412-2,S1412 Style: Women's Material: Pearl Purity: beaded`,
    price: 2.18,
    compareAtPrice: 3.27,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/2b4cf095-95ed-47bb-b526-d654169808b4.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2315890",
      costPrice: 0.87,
      shippingDays: "5-10",
      shippingFee: 1.44,
      processingTime: "3-5 days",
    },
  },
  {
    id: "172",
    slug: "two-color-mirror-phone-case",
    name: `Two-color mirror phone case`,
    description: `Material: tpuPopular elements: solid color`,
    price: 2.23,
    compareAtPrice: 3.35,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/428f975e-6570-4ff9-afc9-359fb100d28a.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSJBHIP00836",
      costPrice: 0.89,
      shippingDays: "5-10",
      shippingFee: 1.45,
      processingTime: "3-5 days",
    },
  },
  {
    id: "173",
    slug: "solid-color-bracket-phone-case-simple",
    name: `Solid Color Bracket Phone Case Simple`,
    description: `Product information:Color: custard custard bracket, White White bracket, rattan Wisteria purple bracket, embroidered green bracket, powder powder bracket, green-blue green-blue bracketApplicable model`,
    price: 2.25,
    compareAtPrice: 3.38,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/3092519c-3a61-46bd-9f53-b0747f52435b.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT2071435",
      costPrice: 0.9,
      shippingDays: "5-10",
      shippingFee: 1.45,
      processingTime: "3-5 days",
    },
  },
  {
    id: "174",
    slug: "bohemian-5pc-green-crystal-bracelets-jewelry-set-for-wo",
    name: `Bohemian 5pc Green Crystal Bracelets Jewelry Set For Women Heart Bracelet Weddin`,
    description: `
 Overview:
 Unique design, stylish and beautiful.Good material, High quality.
 
 Product information:Treatment Process: Diamond Color: S1205HB,S1205-2 Applicable population: Female Style: Women's Mat`,
    price: 2.25,
    compareAtPrice: 3.38,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/94c90b67-271f-411b-87fd-e3daf95ab815.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSL2018329",
      costPrice: 0.9,
      shippingDays: "5-10",
      shippingFee: 1.45,
      processingTime: "3-5 days",
    },
  },
  {
    id: "175",
    slug: "3pcs-vintage-halloween-tree-of-life-and-witch-necklace-",
    name: `3pcs Vintage Halloween Tree Of Life And Witch Necklace Set With Earrings Alloy P`,
    description: `Overview:100% new design and high qualityMust-have for fashion womenHave a beautiful appearanceSpecifications:Material: AlloyProcessing technology: ElectroplatingStyle: HalloweenSet combination: earri`,
    price: 2.25,
    compareAtPrice: 3.38,
    category: "style",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/08/08/07/c72e0795-eb76-4941-99e8-73a9b0777b7c.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJLX2104746",
      costPrice: 0.9,
      shippingDays: "5-10",
      shippingFee: 1.45,
      processingTime: "3-5 days",
    },
  },
  {
    id: "176",
    slug: "samsung-liquid-silicone-phone-case",
    name: `Samsung Liquid Silicone Phone Case`,
    description: `Applicable brand: SamsungStyle: back coverMaterial: SiliconeStyle: SimplePopular elements: solid colorProcess: Plastic molding`,
    price: 2.28,
    compareAtPrice: 3.42,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/20200930/1751720069444.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSJBHGA00143",
      costPrice: 0.91,
      shippingDays: "5-10",
      shippingFee: 1.46,
      processingTime: "3-5 days",
    },
  },
  {
    id: "177",
    slug: "retro-ethnic-style-earrings-and-necklace-set-jewelry",
    name: `Retro Ethnic Style Earrings And Necklace Set Jewelry`,
    description: `Specifications:Applicable people: women Pendant material: Alloy Style: Women's Chain style: Regular chain Material: Alloy Popular elements: EllipseStyle: Retro Set combin`,
    price: 2.33,
    compareAtPrice: 3.5,
    category: "style",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/07/03/03/98ba8aab-506d-4b90-b9b1-bc472e66d224.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJZB2074166",
      costPrice: 0.93,
      shippingDays: "5-10",
      shippingFee: 1.47,
      processingTime: "3-5 days",
    },
  },
  {
    id: "178",
    slug: "the-new-bride-sweater-chain-necklace-jewelry-suite-all-",
    name: `The new bride sweater chain necklace jewelry suite all-match diamond pearl neckl`,
    description: `1`,
    price: 2.33,
    compareAtPrice: 3.5,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/15096384/3531771163_793437558.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJZBHLXN00064",
      costPrice: 0.93,
      shippingDays: "5-10",
      shippingFee: 1.47,
      processingTime: "3-5 days",
    },
  },
  {
    id: "179",
    slug: "outdoor-mobile-phone-waterproof-bag-swimming-diving-tou",
    name: `Outdoor Mobile Phone Waterproof Bag Swimming Diving Touch Screen PVC`,
    description: `Product information:Pattern: solid colorApplicable scenarios: running, outdoor sports, fishing, swimming and wadingColor: white, blue, black, green, matte, matte (new)Fabric: waterproof fabricApplicat`,
    price: 2.35,
    compareAtPrice: 3.53,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2025/02/26/10/be341ed0-5c8e-425d-9607-9091ec1d5894_trans.jpeg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2308580",
      costPrice: 0.94,
      shippingDays: "5-10",
      shippingFee: 1.47,
      processingTime: "3-5 days",
    },
  },
  {
    id: "180",
    slug: "rock-mobile-phone-case",
    name: `Rock mobile phone case`,
    description: `Product No.: Plush TPUApplicable brand: SamsungStyle: back coverMaterial: TPU`,
    price: 2.38,
    compareAtPrice: 3.57,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/20200923/1649409439018.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSJBHGA00135",
      costPrice: 0.95,
      shippingDays: "5-10",
      shippingFee: 1.48,
      processingTime: "3-5 days",
    },
  },
  {
    id: "181",
    slug: "metallic-paint-pc-with-lens-protector-solid-color-phone",
    name: `Metallic Paint PC With Lens Protector Solid Color Phone Case`,
    description: `Product information:Applicable model: AppleFunction: shockproof, anti-wear, anti-fall, anti-fingerprintMaterial: PCStyle: all-inclusiveCraft: FrostedNote∩╝ÜNon-Apple brand products, compatible with IPho`,
    price: 2.38,
    compareAtPrice: 3.57,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/02/04/01/619e92f9-3a72-4dd9-ad36-6bd45d082f50.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJIP1963331",
      costPrice: 0.95,
      shippingDays: "5-10",
      shippingFee: 1.48,
      processingTime: "3-5 days",
    },
  },
  {
    id: "182",
    slug: "tulip-all-inclusive-phone-case",
    name: `Tulip All-inclusive Phone Case`,
    description: `
 Product information:Color: space shell second generation-gradient rose, space shell second generation-gradient Tulip Applicable model: Apple Function: shockproof, anti-wear, anti-fall Material: tpu `,
    price: 2.4,
    compareAtPrice: 3.6,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/7adaf5fe-3bb3-4eb5-a1a3-af914b956e12.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT1976177",
      costPrice: 0.96,
      shippingDays: "5-10",
      shippingFee: 1.48,
      processingTime: "3-5 days",
    },
  },
  {
    id: "183",
    slug: "liquid-silicone-phone-case-lanyard",
    name: `Liquid Silicone Phone Case Lanyard`,
    description: `Product information:Applicable model: AppleMaterial: SiliconePopular elements: lanyardStyle: soft shellStyle: Chinese styleProcess: ElectroplatingNote∩╝ÜNon-Apple brand products, compatible with IPhone `,
    price: 2.4,
    compareAtPrice: 3.6,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/e1f70ab6-7a0e-4b32-b2ea-221ba78a3c3e.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT2308036",
      costPrice: 0.96,
      shippingDays: "5-10",
      shippingFee: 1.48,
      processingTime: "3-5 days",
    },
  },
  {
    id: "184",
    slug: "rhinestone-lens-protector-for-mobile-phones",
    name: `Rhinestone Lens Protector For Mobile Phones`,
    description: `Product information:Color: rhinestone lens protector [Black], rhinestone lens protector [gold], rhinestone lens protector [silver], rhinestone lens protector [pink], rhinestone lens protector [Purple]`,
    price: 2.4,
    compareAtPrice: 3.6,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2025/03/17/10/af2679ad-07b1-449b-b4cb-bf4813050abd_fine.jpeg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2329912",
      costPrice: 0.96,
      shippingDays: "5-10",
      shippingFee: 1.48,
      processingTime: "3-5 days",
    },
  },
  {
    id: "185",
    slug: "3d-screen-magnifier-signal-booster-mobile-screen-lightw",
    name: `3D Screen Magnifier Signal Booster Mobile Screen Lightweight Foldable Magnifying`,
    description: `
 Product name: 12-inch pull-out mobile phone screen amplifierProduct with packaging size: 270X180X15mmProduct color: black/white/redMagnification: 3-4 timesProduct material: ABS plastic + Finier lens`,
    price: 2.4,
    compareAtPrice: 3.6,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/20200228/324374631060.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSJYDSJ00092",
      costPrice: 0.96,
      shippingDays: "5-10",
      shippingFee: 1.48,
      processingTime: "3-5 days",
    },
  },
  {
    id: "186",
    slug: "onion-cutting-knife-household-kitchen-multi-functional-",
    name: `Onion Cutting Knife Household Kitchen Multi-functional Slicer Gadget`,
    description: `Product information:Product description: onion cutting knife Product Size: 11.7 * 1.9cn Color: stainless steel ordinary stylePacking list: 1*Onion Cutting KnifeProduct Image:`,
    price: 2.4,
    compareAtPrice: 3.6,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/05/17/07/14745348-9ece-4530-9481-7e5249fdd167_trans.jpeg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJCF2037492",
      costPrice: 0.96,
      shippingDays: "5-10",
      shippingFee: 1.48,
      processingTime: "3-5 days",
    },
  },
  {
    id: "187",
    slug: "sterling-silver-pendant-necklace-earrings-set-fashion-j",
    name: `Sterling Silver Pendant Necklace Earrings Set Fashion Jewelry Trendy Style Austr`,
    description: `Set combination: earrings + itemsMaterial: AlloyColor: red, green, blue, purple, black, pink, champagne, silver`,
    price: 2.4,
    compareAtPrice: 3.6,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/20200902/74297690788.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJZBGJBS00125",
      costPrice: 0.96,
      shippingDays: "5-10",
      shippingFee: 1.48,
      processingTime: "3-5 days",
    },
  },
  {
    id: "188",
    slug: "fully-flocking-liquid-silicone-phone-case",
    name: `Fully Flocking Liquid Silicone Phone Case`,
    description: `Overview:Applicable product: Apple 13Style: clamshell typeMaterial: liquid silica gelStyle: Japanese and Korean, art, business, cartoon, lovers, fairy, oil painting, lovely, fashion, national style, a`,
    price: 2.43,
    compareAtPrice: 3.65,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/2700f125-a493-467e-b36c-4ec837fe0907.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJIP1599164",
      costPrice: 0.97,
      shippingDays: "5-10",
      shippingFee: 1.49,
      processingTime: "3-5 days",
    },
  },
  {
    id: "189",
    slug: "three-star-s8plus-full-screen-toughened-film",
    name: `Three-star S8Plus full screen toughened film`,
    description: `[packing description] Naked packaging: Film + foam bag bare film weight of about 80 sheets / kg (naked default is not alcohol package). Belt packing: Film + foam bag + alcohol package (click`,
    price: 2.45,
    compareAtPrice: 3.68,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/15277824/1480265532140.png",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJSJSJPB00007",
      costPrice: 0.98,
      shippingDays: "5-10",
      shippingFee: 1.49,
      processingTime: "3-5 days",
    },
  },
  {
    id: "190",
    slug: "suitable-for-14-hd-tempered-film-15-non-hole-dustproof-",
    name: `Suitable For 14 HD Tempered Film 15 Non-hole Dustproof Iphone12pro Full Screen X`,
    description: `
 Product information:Color: non-porous HD tempered film (boxed) Material: tempered glass Size: Apple 15promax,Apple 15pro,Apple 15plus,Apple 15, Apple 14promax,Apple 14pro,Apple 14plus,Apple 14, Appl`,
    price: 2.45,
    compareAtPrice: 3.68,
    category: "tech",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/05/13/03/6b038b9b-b408-44c9-8b49-5ffd733ba46c_trans.jpeg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2034068",
      costPrice: 0.98,
      shippingDays: "5-10",
      shippingFee: 1.49,
      processingTime: "3-5 days",
    },
  },
  {
    id: "191",
    slug: "hollow-pattern-jewelry-set",
    name: `Hollow pattern jewelry set`,
    description: `Material: Alloy`,
    price: 2.45,
    compareAtPrice: 3.68,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/15144768/2399368336_1854979004.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJZBGJZB00142",
      costPrice: 0.98,
      shippingDays: "5-10",
      shippingFee: 1.49,
      processingTime: "3-5 days",
    },
  },
  {
    id: "192",
    slug: "fashion-jewelry-stainless-steel-flower-daisyflower-neck",
    name: `Fashion Jewelry Stainless Steel Flower DaisyFlower Necklace Double Layering Neck`,
    description: `
 Overview:
 Unique design, stylish and beautiful.Good material, High quality.
 
 Product information:Treatment Process: Electroplating Color: gold Chrysanthemum White Shell stud earrings A803, gold C`,
    price: 2.45,
    compareAtPrice: 3.68,
    category: "home",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2024/05/30/05/eaacb051-7d4f-4059-9c23-75297d3c3118.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJLX2045976",
      costPrice: 0.98,
      shippingDays: "5-10",
      shippingFee: 1.49,
      processingTime: "3-5 days",
    },
  },
  {
    id: "193",
    slug: "new-trendy-rings-set-for-women-exaggerated-red-resin-en",
    name: `New Trendy Rings Set For Women Exaggerated Red Resin Enamel Wooden Geometric Fin`,
    description: `
 Product information:Type: Ring Color: HSJ-14900 Inlay material: alloy inlay artificial gemstone/semi-precious stone Style: Unisex Material: Plastic/resin Shape: Geometry
 
 Packing list: 
 5pcs Ring`,
    price: 2.45,
    compareAtPrice: 3.68,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/9ecd8aea-e26a-459b-b1de-b5a6a2a58269.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJLX2056748",
      costPrice: 0.98,
      shippingDays: "5-10",
      shippingFee: 1.49,
      processingTime: "3-5 days",
    },
  },
  {
    id: "194",
    slug: "mobile-phone-tempered-glass-screen-protector",
    name: `Mobile Phone Tempered Glass Screen Protector`,
    description: `- Scratch and wear resistance: With high hardness, it effectively resists scratches from sharp objects like keys and coins in daily life, preventing the phone screen from being scratched and maintaini`,
    price: 2.5,
    compareAtPrice: 3.75,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/f15f2c6b-4058-4f02-be02-589033542f9c.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJPB2377299",
      costPrice: 1,
      shippingDays: "5-10",
      shippingFee: 1.5,
      processingTime: "3-5 days",
    },
  },
  {
    id: "195",
    slug: "water-drop-jewelry-set",
    name: `Water Drop Jewelry Set`,
    description: `Metals Type: Zinc Alloy Jewelry Sets Type: Necklace/Earrings/RingShape\\pattern: Water DropAs you know, the different computers display colors differently,  the color of the actual item may vary slight`,
    price: 2.68,
    compareAtPrice: 4.02,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/15144768/4469246855_1968167221.400x400.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJZBGJZB00077",
      costPrice: 1.07,
      shippingDays: "5-10",
      shippingFee: 1.54,
      processingTime: "3-5 days",
    },
  },
  {
    id: "196",
    slug: "mirror-phone-case-back-cover-type",
    name: `Mirror Phone Case Back Cover Type`,
    description: `Product information :Style: back coverMaterial: PCStyle: simpleColor: piano black, pearl white, Lafite redApplicable models: iPhone 12 Mini (5.4 inch), iPhone 12 (6.1 inch), iPhone 12 Pro (6.1 inch), `,
    price: 2.7,
    compareAtPrice: 4.05,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/621781d1-7cfa-46e7-b897-c9756937a905.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJTA1576234",
      costPrice: 1.08,
      shippingDays: "5-10",
      shippingFee: 1.54,
      processingTime: "3-5 days",
    },
  },
  {
    id: "197",
    slug: "mirror-phone-case-female",
    name: `Mirror Phone Case Female`,
    description: `
 Product information:Applicable models: iPhone 11,iPhone 12,iPhone 8,iPhone 7,iPhone X,iPhone14,iPhone Xs,iPhone Xr,iPhone 7 Plus,iPhone 8 Plus,iPhone 13,iPhone 11 Pro,iPhone 11 Pro Max,iPhone 12 Pro`,
    price: 2.73,
    compareAtPrice: 4.1,
    category: "tech",
    tags: [],
    image: "https://cf.cjdropshipping.com/quick/product/4f5eb057-ddbc-4ed0-81e4-f6c064893505.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJJT2056675",
      costPrice: 1.09,
      shippingDays: "5-10",
      shippingFee: 1.55,
      processingTime: "3-5 days",
    },
  },
  {
    id: "198",
    slug: "kitchen-household-kitchen-knife-deboning-special-slaugh",
    name: `Kitchen Household Kitchen Knife Deboning Special Slaughtered Meat Joint File`,
    description: `Product information :Material: Stainless steelSpecifications: No. 1 deboning kitchen knife, No. 2 deboning kitchen knife, No. 3 deboning kitchen knife, No. 1 knife set, No. 2 No. 3 knife setStyle: new`,
    price: 2.73,
    compareAtPrice: 4.1,
    category: "home",
    tags: [],
    image: "https://cf.cjdropshipping.com/22a7249b-22dd-4ec7-85c5-7397ee101b77.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJCF1412069",
      costPrice: 1.09,
      shippingDays: "5-10",
      shippingFee: 1.55,
      processingTime: "3-5 days",
    },
  },
  {
    id: "199",
    slug: "portable-euro-coin-storage-box-compact-money-organizer-",
    name: `Portable Euro Coin Storage Box - Compact Money Organizer with Built-in Mirror fo`,
    description: `Overview:Keep your loose change neatly organized and always within reach with the CoinSort Pocket Organizer & Change Holder. This compact, cleverly designed case features multiple dedicated slots `,
    price: 2.78,
    compareAtPrice: 4.17,
    category: "home",
    tags: [],
    image: "https://oss-cf.cjdropshipping.com/product/2026/04/07/06/25beb224-7d2d-41db-807d-799bb6124a47.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJYD2818646",
      costPrice: 1.11,
      shippingDays: "5-10",
      shippingFee: 1.56,
      processingTime: "3-5 days",
    },
  },
  {
    id: "200",
    slug: "europe-and-the-united-states-sell-hot-money-network-pea",
    name: `Europe And The United States Sell Hot Money Network Pearl Necklace Set Bridal Je`,
    description: `   

`,
    price: 2.78,
    compareAtPrice: 4.17,
    category: "style",
    tags: [],
    image: "https://cf.cjdropshipping.com/15096384/3924914869_773361498.jpg",
    createdAt: "2026-06-15",
    status: "live" as const,
    shippingFrom: "China",
    supplier: {
      source: "cj-dropshipping" as const,
      sku: "CJZBHLXN00042",
      costPrice: 1.11,
      shippingDays: "5-10",
      shippingFee: 1.56,
      processingTime: "3-5 days",
    },
  },
];

