import type { Product } from "./types";

export const consumerElectronics: Product[] = [
  {
    id: "ce1",
    slug: "smart-tv-55-inch",
    name: "4K Ultra HD Smart TV",
    description: "55-inch 4K Smart TV with streaming apps and voice control.",
    price: 499.99,
    compareAtPrice: 699.99,
    category: "consumer-electronics",
    tags: ["tv", "smart", "streaming", "4k"],
    image: "https://images.unsplash.com/photo-1593359416365-3a3b9f2c1e2e?w=500&auto=format&fit=crop&q=60",
    images: [
      "https://images.unsplash.com/photo-1593359416365-3a3b9f2c1e2e?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1620889543939-6c4a3c3b9d8e?w=500&auto=format&fit=crop&q=60",
    ],
    rating: 4.7,
    reviewCount: 156,
    createdAt: "2026-06-15",
    status: "live",
    weight: "25kg",
    inventory: 34,
    shippingFrom: "China",
    shippingMethods: [
      {
        name: "Standard Shipping",
        fee: 29.99,
        processingDays: "3-5 days",
        deliveryDays: "7-12 days",
        tracking: "Full tracking",
      },
      {
        name: "Express Shipping",
        fee: 49.99,
        processingDays: "1-2 days",
        deliveryDays: "3-5 days",
        tracking: "Full tracking",
      },
    ],
    totalLandedCost: 559.48,
    supplier: {
      source: "cj-dropshipping",
      sku: "TV-55-4K-SMART-001",
      costPrice: 500.00,
      shippingDays: "5",
      shippingFee: 29.99,
      processingTime: "3-5 days",
      notes: "HDR10+ support, Netflix, Disney+ pre-installed",
    },
  },
  {
    id: "ce2",
    slug: "smart-speaker-with-alexa",
    name: "Smart Speaker with Alexa",
    description: "Compact smart speaker with built-in Alexa voice assistant and premium sound quality.",
    price: 79.99,
    compareAtPrice: 129.99,
    category: "consumer-electronics",
    tags: ["speaker", "alexa", "smart", "voice"],
    image: "https://images.unsplash.com/photo-1586201375761-83865001e8ce?w=500&auto=format&fit=crop&q=60",
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e8ce?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1620889543939-6c4a3c3b9d8e?w=500&auto=format&fit=crop&q=60",
    ],
    rating: 4.8,
    reviewCount: 203,
    createdAt: "2026-06-10",
    status: "live",
    weight: "1.2kg",
    inventory: 145,
    shippingFrom: "China",
    shippingMethods: [
      {
        name: "Standard Shipping",
        fee: 9.99,
        processingDays: "3-5 days",
        deliveryDays: "7-12 days",
        tracking: "Full tracking",
      },
    ],
    totalLandedCost: 89.98,
    supplier: {
      source: "cj-dropshipping",
      sku: "SPKR-ALEXA-002",
      costPrice: 80.00,
      shippingDays: "4",
      shippingFee: 9.99,
      processingTime: "3-5 days",
      notes: "Wi-Fi connected, multi-room audio capable",
    },
  },
  {
    id: "ce3",
    slug: "wireless-earbuds-pro",
    name: "Premium Wireless Earbuds",
    description: "High-fidelity wireless earbuds with active noise cancellation and long battery life.",
    price: 129.99,
    compareAtPrice: 199.99,
    category: "consumer-electronics",
    tags: ["earbuds", "wireless", "bluetooth", "noise-cancellation"],
    image: "https://images.unsplash.com/photo-1505740420237-3c6c9893b8d6?w=500&auto=format&fit=crop&q=60",
    images: [
      "https://images.unsplash.com/photo-1505740420237-3c6c9893b8d6?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1620889543939-6c4a3c3b9d8e?w=500&auto=format&fit=crop&q=60",
    ],
    rating: 4.6,
    reviewCount: 89,
    createdAt: "2026-06-12",
    status: "live",
    weight: "0.5kg",
    inventory: 167,
    shippingFrom: "China",
    shippingMethods: [
      {
        name: "Standard Shipping",
        fee: 12.99,
        processingDays: "3-5 days",
        deliveryDays: "7-12 days",
        tracking: "Full tracking",
      },
    ],
    totalLandedCost: 139.98,
    supplier: {
      source: "cj-dropshipping",
      sku: "EARBUDS-WIRELESS-003",
      costPrice: 120.00,
      shippingDays: "4",
      shippingFee: 12.99,
      processingTime: "3-5 days",
      notes: "IPX5 water resistance, charging case included",
    },
  },
  {
    id: "ce4",
    slug: "smart-home-hub",
    name: "Smart Home Hub",
    description: "Central hub for controlling smart home devices with voice commands and automation.",
    price: 149.99,
    compareAtPrice: 249.99,
    category: "consumer-electronics",
    tags: ["smart", "home", "hub", "automation"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop&q=60",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1620889543939-6c4a3c3b9d8e?w=500&auto=format&fit=crop&q=60",
    ],
    rating: 4.7,
    reviewCount: 98,
    createdAt: "2026-06-08",
    status: "live",
    weight: "2.1kg",
    inventory: 78,
    shippingFrom: "China",
    shippingMethods: [
      {
        name: "Standard Shipping",
        fee: 15.99,
        processingDays: "3-5 days",
        deliveryDays: "7-12 days",
        tracking: "Full tracking",
      },
    ],
    totalLandedCost: 164.98,
    supplier: {
      source: "cj-dropshipping",
      sku: "HUB-SMARTHOME-004",
      costPrice: 145.00,
      shippingDays: "5",
      shippingFee: 15.99,
      processingTime: "3-5 days",
      notes: "Compatible with Alexa, Google Home, Apple HomeKit",
    },
  },
  {
    id: "ce5",
    slug: "gaming-laptop-15-inch",
    name: "Gaming Laptop",
    description: "High-performance gaming laptop with RTX graphics and fast refresh rate display.",
    price: 1299.99,
    compareAtPrice: 1799.99,
    category: "consumer-electronics",
    tags: ["laptop", "gaming", "rtx", "performance"],
    image: "https://images.unsplash.com/photo-1593359416365-3a3b9f2c1e2e?w=500&auto=format&fit=crop&q=60",
    images: [
      "https://images.unsplash.com/photo-1593359416365-3a3b9f2c1e2e?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1620889543939-6c4a3c3b9d8e?w=500&auto=format&fit=crop&q=60",
    ],
    rating: 4.8,
    reviewCount: 67,
    createdAt: "2026-06-14",
    status: "live",
    weight: "3.2kg",
    inventory: 23,
    shippingFrom: "China",
    shippingMethods: [
      {
        name: "Standard Shipping",
        fee: 25.99,
        processingDays: "3-5 days",
        deliveryDays: "7-12 days",
        tracking: "Full tracking",
      },
    ],
    totalLandedCost: 1325.98,
    supplier: {
      source: "cj-dropshipping",
      sku: "LAPTOP-GAMING-005",
      costPrice: 1280.00,
      shippingDays: "6",
      shippingFee: 25.99,
      processingTime: "3-5 days",
      notes: "RTX 3060 Ti, 16GB RAM, 512GB SSD",
    },
  },
];