import type { Product } from "./types";

export const petSupplies: Product[] = [
  {
    id: "pet1",
    slug: "dog-bed-orthopedic",
    name: "Orthopedic Dog Bed",
    description: "Memory foam orthopedic dog bed with waterproof cover for large breeds.",
    price: 89.99,
    compareAtPrice: 149.99,
    category: "home",
    tags: ["dog", "bed", "orthopedic", "pet"],
    image: "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=500&auto=format&fit=crop&q=60",
    images: [
      "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop&q=60",
    ],
    rating: 4.8,
    reviewCount: 124,
    createdAt: "2026-06-15",
    status: "live",
    weight: "4.5kg",
    inventory: 67,
    shippingFrom: "China",
    shippingMethods: [
      {
        name: "Standard Shipping",
        fee: 15.99,
        processingDays: "3-5 days",
        deliveryDays: "7-12 days",
        tracking: "Full tracking",
      },
    ],
    totalLandedCost: 104.98,
    supplier: {
      source: "cj-dropshipping",
      sku: "PET-BED-ORTHO-001",
      costPrice: 80.00,
      shippingDays: "5",
      shippingFee: 15.99,
      processingTime: "3-5 days",
      notes: "Waterproof removable cover, non-slip bottom",
    },
  },
  {
    id: "pet2",
    slug: "cat-tree-scratcher",
    name: "Multi-Level Cat Tree",
    description: "Tall cat tree with scratching posts, platforms, and hideaway for active cats.",
    price: 159.99,
    compareAtPrice: 249.99,
    category: "home",
    tags: ["cat", "tree", "scratcher", "climbing"],
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500&auto=format&fit=crop&q=60",
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop&q=60",
    ],
    rating: 4.7,
    reviewCount: 89,
    createdAt: "2026-06-10",
    status: "live",
    weight: "12kg",
    inventory: 34,
    shippingFrom: "China",
    shippingMethods: [
      {
        name: "Standard Shipping",
        fee: 25.99,
        processingDays: "3-5 days",
        deliveryDays: "7-12 days",
        tracking: "Full tracking",
      },
    ],
    totalLandedCost: 184.98,
    supplier: {
      source: "cj-dropshipping",
      sku: "PET-CAT-TREE-002",
      costPrice: 155.00,
      shippingDays: "6",
      shippingFee: 25.99,
      processingTime: "3-5 days",
      notes: "Sisal rope posts, plush platforms, includes toys",
    },
  },
  {
    id: "pet3",
    slug: "automatic-pet-feeder",
    name: "Smart Automatic Pet Feeder",
    description: "WiFi-enabled automatic pet feeder with app control and camera for monitoring.",
    price: 129.99,
    compareAtPrice: 199.99,
    category: "consumer-electronics",
    tags: ["feeder", "smart", "wifi", "camera"],
    image: "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=500&auto=format&fit=crop&q=60",
    images: [
      "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop&q=60",
    ],
    rating: 4.6,
    reviewCount: 56,
    createdAt: "2026-06-12",
    status: "live",
    weight: "2.8kg",
    inventory: 78,
    shippingFrom: "China",
    shippingMethods: [
      {
        name: "Standard Shipping",
        fee: 12.99,
        processingDays: "3-5 days",
        deliveryDays: "7-12 days",
        tracking: "Full tracking",
      },
    ],
    totalLandedCost: 142.98,
    supplier: {
      source: "cj-dropshipping",
      sku: "PET-FEEDER-SMART-003",
      costPrice: 125.00,
      shippingDays: "4",
      shippingFee: 12.99,
      processingTime: "3-5 days",
      notes: "App scheduling, portion control, 1080p camera",
    },
  },
  {
    id: "pet4",
    slug: "pet-grooming-kit",
    name: "Complete Pet Grooming Kit",
    description: "Professional grooming kit with clippers, brushes, nail trimmer, and combs.",
    price: 49.99,
    compareAtPrice: 79.99,
    category: "home",
    tags: ["grooming", "clippers", "brush", "nails"],
    image: "https://images.unsplash.com/photo-1586201375761-83865001e8ce?w=500&auto=format&fit=crop&q=60",
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e8ce?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop&q=60",
    ],
    rating: 4.5,
    reviewCount: 78,
    createdAt: "2026-06-08",
    status: "live",
    weight: "1.5kg",
    inventory: 145,
    shippingFrom: "China",
    shippingMethods: [
      {
        name: "Standard Shipping",
        fee: 9.99,
        processingDays: "3-5 days",
        deliveryDays: "7-12 days",
        tracking: "Full tracking",
      },
    ],
    totalLandedCost: 59.98,
    supplier: {
      source: "cj-dropshipping",
      sku: "PET-GROOMING-004",
      costPrice: 45.00,
      shippingDays: "4",
      shippingFee: 9.99,
      processingTime: "3-5 days",
      notes: "Quiet motor, 4 guard combs, stainless steel blades",
    },
  },
];